CREATE WAREHOUSE IF NOT EXISTS GROCERY_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE

CREATE DATABASE IF NOT EXISTS GROCERY_DB

CREATE SCHEMA IF NOT EXISTS GROCERY_DB.RAW

-- CSV file --
CREATE FILE FORMAT IF NOT EXISTS GROCERY_DB.RAW.CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE
    ENCODING = 'UTF8';

-- Internal stage for Project Hammer CSV uploads --
CREATE STAGE IF NOT EXISTS GROCERY_DB.RAW.HAMMER_STAGE
    FILE_FORMAT = GROCERY_DB.RAW.CSV_FORMAT

SHOW WAREHOUSES LIKE 'GROCERY_WH';
SHOW SCHEMAS IN DATABASE GROCERY_DB;
