USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON DATABASE GROCERY_DB TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA GROCERY_DB.RAW TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON FILE FORMAT GROCERY_DB.RAW.CSV_FORMAT TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STAGE GROCERY_DB.RAW.HAMMER_STAGE TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE GROCERY_WH TO ROLE SYSADMIN COPY CURRENT GRANTS;